安全文档老文档移植、目录结构提交
yunify/qingcloud-docs pull request #27
Opened 2020-10-30 06:41 UTC by mattaug

2020-11-17 09:20 UTC, Xuanwo requested changes

2020-11-17 09:20 UTC, Xuanwo commented on content/security/ddos_defense/_index.md
> +# DDoS 攻击防护[¶](#ddos)
Trim extra `¶` please

2020-11-17 09:20 UTC, Xuanwo commented on content/security/ddos_defense/manual/antiddos_user_guide.md
> +## 创建[¶](#create)
ditto

2020-11-17 09:20 UTC, Xuanwo commented on content/security/ddos_defense/manual/antiddos_user_guide.md
> +## FAQ[¶](#faq)
ditto

2020-11-17 09:20 UTC, Xuanwo commented on content/security/network_acl/manual/acl_user_guide.md
> +## 创建[¶](#create)
ditto

2020-11-17 09:20 UTC, Xuanwo commented on content/security/network_acl/manual/acl_user_guide.md
> +## FAQ[¶](#faq)
ditto

2020-11-17 09:20 UTC, Xuanwo commented on content/security/security_group/manual/sg_user_guide.md
> +  通过策略配置，防火墙能极大地提高一个内部网络或主机的安全性，并过滤不安全的服务，从而降低内部网络或主机的风险。
Trim extra space here.

2020-11-17 09:20 UTC, Xuanwo commented on content/security/waf/faq/faq.md
> +![图片](/computing/_images/image-1568884268968.png)
Looks like a broken link to image

2020-11-17 09:20 UTC, Xuanwo commented
修复 review 中提到的问题，然后确认 CI 通过之后就可以 merge 了

2020-11-18 02:57 UTC, FeynmanZhou commented
@mattaug 
我在 netlify 预览里看到的样式和图片都是乱的，这个确定有在本地浏览器预览检查过？而且缺少文档的独立子页面，你可以看一下 IAM 的文档，在另一个 PR 里
https://5fb3b5e1a30efb0008958908--musing-yonath-8e9db1.netlify.app/

2020-11-20 04:07 UTC, mattaug commented
修改图片路径，去掉了多余的空格和 ¶ 符号

2020-11-20 09:20 UTC, Xuanwo approved these changes

2020-11-20 09:20 UTC, merged